FROM openjdk:8-jdk-alpine

COPY target/config-server.jar /opt/
COPY entrypoint.sh /opt/

RUN chmod 777 /opt/entrypoint.sh

EXPOSE 9999

VOLUME /opt/config-repo

CMD ["java", "-jar", "/opt/config-server.jar"]