server:
  port: 8090

spring:
  application:
    name: zuul-proxy

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}

zuul:
  routes:
    ping:
      path: /ping/**
      serviceId: eureka-client
      stripPrefix: false